version: '1'
services:
  systemBackground:
    image: systemBackground
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - spring.profiles.active=dev
    volumes:
        - "/home/jenkins_home:/var/jenkins_home"
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/usr/bin/docker:/usr/bin/docker"